---
title: Sawyer Hollenshead
url: http://sawyerh.com
timezone: America/New_York
collections:
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- Copywriting.md
- README.md
- tmp
- ".gitignore"
- "node_modules/"
- "bower_components/"
- package.json
- webpack.config.js